name: neroia_app
description: "Neroia Flutter App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_udid: ^4.0.0
  flutter_native_splash: ^2.4.5

  # UI
  hugeicons: ^0.0.7
  smooth_sheets: ^0.10.2
  flutter_svg: ^2.1.0
  flutter_spinkit: ^5.2.1

  # Tracking
  usercentrics_sdk: ^2.18.9
  posthog_flutter: ^4.10.4

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Navigation & Routing
  go_router: ^14.8.1
  store_redirect: ^2.0.4

  # Networking & Database
  envied: ^1.1.1
  flutter_secure_storage: ^9.2.4
  rxdart: ^0.28.0

  # Multi Language
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  collection: ^1.19.1

  # Reporting
  logger: ^2.5.0
  sentry_flutter: ^8.14.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  protoc_plugin: ^21.1.2

  # Code Generation
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  go_router_builder: ^2.8.2
  envied_generator: ^1.1.1
  freezed: ^3.0.3
  json_serializable: ^6.9.4

  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  background_image: assets/splash.jpg
  image: assets/icon.png

  android_12:
    background_image: assets/splash.jpg
    image: assets/icon.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
